version: "3"

services:

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - COMPOSER_GITHUB_TOKEN=${COMPOSER_GITHUB_TOKEN}
    image: ${APP_NAME}_php_image
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9091:9000"

  composer:
    image: ${APP_NAME}_php_image
    depends_on:
      - php
    container_name: ${APP_NAME}_composer
    profiles:
      - development # this ensures the container is not created when launching "docker-compose up"
    volumes:
      - ./:/var/www/html
    entrypoint: [ 'composer' ]
    # NOTE:  It is possible to launch composer command using this container.
    # Ex. docker-compose run --rm composer update

  artisan:
    image: ${APP_NAME}_php_image
    depends_on:
      - php
    container_name: ${APP_NAME}_artisan
    profiles:
      - development
    volumes:
      - ./:/var/www/html
    entrypoint: [ 'php', 'artisan' ]

  test:
    image: ${APP_NAME}_php_image
    depends_on:
      - php
    container_name: ${APP_NAME}_phpunit
    profiles:
      - development
    volumes:
      - ./:/var/www/html
    #entrypoint: [ 'vendor/bin/phpunit' ]
    entrypoint: [ 'php', 'artisan', 'test' ]

  npm:
    image: node:14-alpine3.13
    profiles:
      - development
    container_name: ${APP_NAME}_npm
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    entrypoint: [ 'npm' ]

  db:
    image: postgres:9.6
    container_name: ${APP_NAME}_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - LC_COLLATE=C.UTF-8
      - LC_CTYPE=C.UTF-8
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    command: -p ${DB_PORT}
    # NOTE: The first time the container is launched (docker-compose up), it might take some time to create the db; during
    # this time the connection may be unavailable.
    #
    # Populate DB with: docker-compose run --rm artisan imet:init_db

